version: '2.1'
services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    ports:
      - 27018:27018

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"